title: thefastman
description: My GitHub Pages site with Jekyll
url: https://thefastman.github.io
theme: minima

# Optional, nice-to-haves:
author: thefastman
minima:
  skin: auto           # light/dark auto
  social_links:
    github: thefastman
